CREATE OR REPLACE TABLE bronze.data AS
SELECT * FROM bronze.PART0
UNION ALL
SELECT * FROM bronze.PART1
UNION ALL
SELECT * FROM bronze.PART2
UNION ALL
SELECT * FROM bronze.PART3
UNION ALL
SELECT * FROM bronze.PART4
UNION ALL
SELECT * FROM bronze.PART5
UNION ALL
SELECT * FROM bronze.PART6
UNION ALL
SELECT * FROM bronze.PART7
UNION ALL
SELECT * FROM bronze.PART8;